[workspace]
resolver = "2"
members = ["crates/casacure", "crates/casacure-python"]

[workspace.dependencies]
casacure = { path = "crates/casacure", version = "3.8.10" }

[workspace.package]
version = "3.8.10"
authors = ["Tim Molteno <tim@elec.ac.nz>"]
edition = "2021"
license = "LGPL-3.0-or-later"
repository = "https://github.com/tmolteno/casacure"
description = "A Rust replacement for the casacore table system, with Python bindings"

[profile.release]
lto = true
